### ISSUE TITLE
Script no longer gets current IP from Cloudflare

### ISSUE THREAD

**Issue by Fexiven** [DatDraggy/cloudflare-bash-ip-updater#1]
The Script doesn't get the currently set IP from Cloudflare.

Maybe that's the problem:
https://community.cloudflare.com/t/no-longer-able-to-update-dns-records-via-api/143942

**Comment by DatDraggy** [comment]
Looks like the grep is the issue. Apparently now there is a space between "content": and "ip". 

I'm conflicted whether to require awk to use it's json query capability or remain with the grep regex approach
